namespace: wazuh

global:
  imagePullPolicy: IfNotPresent

manager:
  image: wazuh/wazuh-manager:4.7.3
  replicas: 1

indexer:
  image: wazuh/wazuh-indexer:4.7.3
  replicas: 1
  storage:
    size: 10Gi

dashboard:
  image: wazuh/wazuh-dashboard:4.7.3
  replicas: 1
