apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wazuh
  template:
    metadata:
      labels:
        app: wazuh
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
