apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-manager
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      app: wazuh-manager
  template:
    metadata:
      labels:
        app: wazuh-manager
    spec:
      containers:
        - name: manager
          image: {{ .Values.manager.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 1514
